---
abstract: 'Consistent object-oriented interface for generating random numbers'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::MockRandom: 0.95
  Test::More: 0
  Test::Number::Delta: 0.14
  blib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Random-OO
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Math::Random::OO:
    file: lib/Math/Random/OO.pm
    version: 0.22
  Math::Random::OO::Bootstrap:
    file: lib/Math/Random/OO/Bootstrap.pm
    version: 0.22
  Math::Random::OO::Normal:
    file: lib/Math/Random/OO/Normal.pm
    version: 0.22
  Math::Random::OO::Uniform:
    file: lib/Math/Random/OO/Uniform.pm
    version: 0.22
  Math::Random::OO::UniformInt:
    file: lib/Math/Random/OO/UniformInt.pm
    version: 0.22
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Params::Validate: 0.76
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/math-random-oo/issues
  homepage: https://metacpan.org/release/Math-Random-OO
  repository: git://github.com/dagolden/math-random-oo.git
version: 0.22
