--- #YAML:1.0
name: Math-Random-OO
version: 0.11
author:
  - david@dagolden.com
abstract: |-
  Consistent object-oriented interface for generating random
  numbers
license: perl
requires:
  Attribute::Util: 0.02
  Class::Accessor::Fast: 0.19
  Params::Validate: 0.74
build_requires:
  Test::Exception: 0.19
  Test::MockRandom: 0.93
  Test::Number::Delta: 0.11
  Test::Simple: 0.53
provides:
  Math::Random::OO:
    file: lib/Math/Random/OO.pm
    version: 0.11
  Math::Random::OO::Bootstrap:
    file: lib/Math/Random/OO/Bootstrap.pm
    version: 0.11
  Math::Random::OO::Normal:
    file: lib/Math/Random/OO/Normal.pm
    version: 0.11
  Math::Random::OO::Uniform:
    file: lib/Math/Random/OO/Uniform.pm
    version: 0.11
  Math::Random::OO::UniformInt:
    file: lib/Math/Random/OO/UniformInt.pm
    version: 0.11
generated_by: Module::Build version 0.2606
