---
name: Math-Random-OO
version: 0.14
author:
  - David A Golden <dagolden@cpan.org>
abstract: |-
  Consistent object-oriented interface for generating random
  numbers
license: perl
requires:
  Attribute::Util: 0.02
  Params::Validate: 0.76
  base: 2.06
  perl: 5.006
build_requires:
  Test::Distribution: 1.18
  Test::Exception: 0.2
  Test::MockRandom: 0.95
  Test::More: 0.6
  Test::Number::Delta: 0.14
  Test::Pod: 1.2
  Test::Pod::Coverage: 1.06
provides:
  Math::Random::OO:
    file: lib/Math/Random/OO.pm
    version: 0.14
  Math::Random::OO::Bootstrap:
    file: lib/Math/Random/OO/Bootstrap.pm
    version: 0.14
  Math::Random::OO::Normal:
    file: lib/Math/Random/OO/Normal.pm
    version: 0.14
  Math::Random::OO::Uniform:
    file: lib/Math/Random/OO/Uniform.pm
    version: 0.14
  Math::Random::OO::UniformInt:
    file: lib/Math/Random/OO/UniformInt.pm
    version: 0.14
generated_by: Module::Build version 0.2608
